name: windows-build-rel

on: [push, pull_request]
  
jobs:
 build-windows-rel:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
       submodules: 'true'
       lfs: 'true'
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Set env
      id: env
      run: |
        xmake g -c
        xmake l setup.lua
    - name: Release
      run: |
        xmake f -m release --toolchain=msvc -c -y -v --policies=build.ccache:n
        xmake -y -v
    - name: UploadArtifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build
